INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.02,'2023-04-23','2023-04-23','ACTUAL');
INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.03,'2023-04-23','2023-04-23','ANTERIOR');
INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.04,'2023-04-23','2023-04-23','ANTERIOR');
INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.05,'2023-04-23','2023-04-23','ANTERIOR');
INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.06,'2023-04-23','2023-04-23','ANTERIOR');
INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.07,'2023-04-23','2023-04-23','ANTERIOR');
INSERT INTO hospital.historial_porcentajes(porcentaje,fecha_inicial,fecha_final,estado) VALUES(0.08,'2023-04-23','2023-04-23','ANTERIOR');

INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadA','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadB','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadC','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadD','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadE','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadF','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadG','descripcion');
INSERT INTO hospital.especialidad(nombre,descripcion) VALUES('especialidadH','descripcion');

INSERT INTO hospital.usuario (nombre,username,password,email,fecha_nacimiento,saldo,tipo,direccion,cui) 
VALUES
('nombre','username1','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'ADMIN','Direccion','cui'),
('nombre','username2','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'MEDICO','Direccion','cui'),
('nombre','username3','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'MEDICO','Direccion','cui'),
('nombre','username4','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'MEDICO','Direccion','cui'),
('nombre','username5','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username6','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username7','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username8','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username9','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username10','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username11','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'PACIENTE','Direccion','cui'),
('nombre','username12','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'LABORATORIO','Direccion','cui'),
('nombre','username13','GuCcqSl362rDLECeQukKWg==','email@com','2023-04-23',500,'LABORATORIO','Direccion','cui');
